### ISSUE TITLE
Tipografías en sección "Software libre"

### ISSUE THREAD

**Issue by enochelrojo** [matiasnoriega/web-gnuno#17]
La fuente en la sección "Software libre" no coincide con la utilizada en el resto del sitio.
![gnuno-captura1](https://user-images.githubusercontent.com/25081106/49327011-cdd48c80-f539-11e8-91fd-b16f94e89e41.png)
(quería probar los issues :-p)

**Comment by matiasnoriega** [comment]
Hay que volver a poner monospace en todo el sitio!

**Comment by matiasnoriega** [comment]
Solucionado en el último commit.
